services:
  nateb.xyz:
    image: nateb.xyz:latest
    networks:
      - caddy_ingress
    environment:
      - VITE_DEPLOY_COMMIT
      - VITE_DEPLOY_TIMESTAMP
      - ARTICLES_DIRNAME
      - SQLITE_FILENAME
    volumes:
      - ./data:/data
      - ./articles:/articles
    labels:
      caddy: nateb.xyz
      caddy.reverse_proxy: '{{upstreams 3000}}'
