services:
  caddy_proxy:
    image: lucaslorentz/caddy-docker-proxy:2.8-alpine
    ports:
      - target: 80
        published: 80
        protocol: tcp
      - target: 443
        published: 443
        protocol: tcp
    environment:
      CADDY_INGRESS_NETWORKS: ${COMPOSE_PROJECT_NAME}_caddy_ingress
    networks:
      - caddy_ingress
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    restart: unless-stopped

  site:
    image: node:${NODE_MAJOR}.${NODE_MINOR}-bookworm-slim
    working_dir: /app/site
    command: ['npm', 'run', 'dev']
    environment:
      - ENV=development
      - VITE_DOMAIN
      - SITE_SQLITE_FILE
    networks:
      - default
      - caddy_ingress
    volumes:
      - .:/app
    labels:
      caddy: ${VITE_DOMAIN}
      caddy.reverse_proxy: '{{upstreams 80}}'

networks:
  caddy_ingress:
    driver: bridge

volumes:
  caddy_data: {}
