services:
  caddy_proxy:
    image: lucaslorentz/caddy-docker-proxy:2.8.3-alpine
    ports:
      - target: 80
        published: 80
        protocol: tcp
      - target: 443
        published: 443
        protocol: tcp
    environment:
      CADDY_INGRESS_NETWORKS: natebxyz_caddy_ingress
    networks:
      - caddy_ingress
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    restart: unless-stopped

networks:
  caddy_ingress:
    driver: bridge

volumes:
  caddy_data: {}
